name: getBranchName
on: [pull_request, push, create]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo ${GITHUB_REF#refs/heads/}
        id: extract_branch

      # extract branch name on pull request
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo ${GITHUB_HEAD_REF}

      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
      
      - name: Trigger script
        run: .github/env.sh
        env:
          BRANCH_head: ${{ github.head_ref }}
          BRANCH_bump: bump/${{ steps.finish.outputs.version }}
          BRANCH_base: ${{ github.base_ref }}
          BRANCH_event: '${{ github.event.ref }}'
