name: getBranchName
on: [pull_request, push]

jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      # extract branch name
      - name: start release or hotfix version bump
        id: start
        run: .github/env.sh
